### PR TITLE
fix: timeout on publish

### PR DESCRIPTION
**Pull request by line-o**
- cache package metadata in meta/package.xml
- extract package metadata only from newly published packages
- use cached metadata to build apps.xml
- move metadata to separate meta collection
- publish directly on upload
- the "publish" button only returns to list

### CODE REVIEW

**Comment by line-o** [comment]
@joewiz I can confirm that uploading multiple packages in one go is possible.

**Comment by line-o** [comment]
Tested... fixed... and good to go.

**Comment by joewiz** [comment]
I'm having a little trouble testing this, because after building the xar and installing it into Dashboard, I get:

> Error found while processing repo.xml: err:XQST0034 error found while loading module scanrepo: Error while loading module modules/scan.xql: Prolog has more than one imported module that defines the function: {http://expath.org/ns/crypto}generate-signature#7 [at line 6, column 1]

I think this is the known issue you've mentioned with the crypto library under 5.3.0... 

Is the best approach for now to use an earlier version of eXist for testing this PR? Which version?

**Comment by duncdrum** [comment]
*cough* test on ci *cough*

**Comment by line-o** [comment]
Ah @joewiz - of course you need to test this on exist >= 5.2.0 and crypto 1.0.0

**Comment by line-o** [comment]
@duncdrum CI is definitely needed but would only show us the same issue with crypto on 5.3.0-SNAPSHOT

**Review by joewiz — APPROVED** [review]
Everything works for me.

**Pull request merged**
